# XDC Constraints for Microphone Array
# Generated by MicArrayTool
#

set_property IOSTANDARD LVCMOS33 [get_ports SYNC_IN]
set_property PACKAGE_PIN U12 [get_ports SYNC_IN]
# MCLK1 - IO_B34_LP14 (BANK 34)
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_OUT]
set_property PACKAGE_PIN T12 [get_ports SYNC_OUT]
# MCLK2 - IO_B34_LP11 (BANK 34)
# MCLK0 - IO_B13_LP21 (BANK 13)
set_property IOSTANDARD LVCMOS33 [get_ports M0_CLK]
set_property PACKAGE_PIN V11 [get_ports M0_CLK]
# MCLK1 - IO_B34_LP14 (BANK 34)
set_property IOSTANDARD LVCMOS33 [get_ports M1_CLK]
set_property PACKAGE_PIN N20 [get_ports M1_CLK]
# MCLK2 - IO_B34_LP11 (BANK 34)
set_property IOSTANDARD LVCMOS33 [get_ports M2_CLK]
set_property PACKAGE_PIN U14 [get_ports M2_CLK]
# LED_DI - IO_B34_LN23 (BANK 34)
set_property IOSTANDARD LVCMOS33 [get_ports LEDS]
set_property PACKAGE_PIN P18 [get_ports LEDS]
set_property IOSTANDARD LVCMOS33 [get_ports {M_DATA[*]}]
# Total microphones: 8
# GPIO ports needed: 8 (each GPIO samples 2 mics: rising + falling edge)
#
# Sampling scheme:
#   - Even mic index (M0, M2, M4...): sampled on RISING edge
#   - Odd mic index (M1, M3, M5...): sampled on FALLING edge
#
# Selected mics: [0, 3, 47, 43, 39, 59, 55, 51]

# D0 -> M_DATA[0]
# Mics: M0(rising)
# IO: IO_B34_LP12
set_property PACKAGE_PIN U18 [get_ports {M_DATA[0]}]

# D2 -> M_DATA[1]
# Mics: M3(falling)
# IO: IO_B13_LN18
set_property PACKAGE_PIN Y11 [get_ports {M_DATA[1]}]

# D38 -> M_DATA[2]
# Mics: M39(falling)
# IO: IO_B34_LN24
set_property PACKAGE_PIN P16 [get_ports {M_DATA[2]}]

# D42 -> M_DATA[3]
# Mics: M43(falling)
# IO: IO_B13_LP19
set_property PACKAGE_PIN T5 [get_ports {M_DATA[3]}]

# D46 -> M_DATA[4]
# Mics: M47(falling)
# IO: IO_B13_LP14
set_property PACKAGE_PIN Y9 [get_ports {M_DATA[4]}]

# D50 -> M_DATA[5]
# Mics: M51(falling)
# IO: IO_B13_LP16
set_property PACKAGE_PIN W10 [get_ports {M_DATA[5]}]

# D54 -> M_DATA[6]
# Mics: M55(falling)
# IO: IO_B34_LN20
set_property PACKAGE_PIN R18 [get_ports {M_DATA[6]}]

# D58 -> M_DATA[7]
# Mics: M59(falling)
# IO: IO_B34_25
set_property PACKAGE_PIN T19 [get_ports {M_DATA[7]}]
