# set_property CFGBVS VCCO [current_design]
# set_property CONFIG_VOLTAGE 3.3 [current_design]

# set_property SLEW SLOW [get_ports M1_DATA]
# set_property KEEPER true [get_ports M1_DATA]


# M59 M58 ------------D58

# MCLK0 - IO_B13_LP21 (BANK 13)
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_IN]
set_property PACKAGE_PIN U12 [get_ports SYNC_IN]
# MCLK1 - IO_B34_LP14 (BANK 34)
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_OUT]
set_property PACKAGE_PIN T12 [get_ports SYNC_OUT]

# MCLK2 - IO_B34_LP11 (BANK 34)
# MCLK0 - IO_B13_LP21 (BANK 13)
set_property IOSTANDARD LVCMOS33 [get_ports M0_CLK]
set_property PACKAGE_PIN V11 [get_ports M0_CLK]
# MCLK1 - IO_B34_LP14 (BANK 34)
set_property IOSTANDARD LVCMOS33 [get_ports M1_CLK]
set_property PACKAGE_PIN N20 [get_ports M1_CLK]
# MCLK2 - IO_B34_LP11 (BANK 34)
set_property IOSTANDARD LVCMOS33 [get_ports M2_CLK]
set_property PACKAGE_PIN U14 [get_ports M2_CLK]

# LED_DI - IO_B34_LN23 (BANK 34)
set_property IOSTANDARD LVCMOS33 [get_ports LEDS]
set_property PACKAGE_PIN P18 [get_ports LEDS]

set_property IOSTANDARD LVCMOS33 [get_ports {M_DATA[*]}]

## XDC Constraints for Selected Microphones
# Generated by MicArrayTool
# Selection: 60 microphones
# Microphone indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]

# M0 - D0 -> M_DATA[0]
# IO Pin: IO_B34_LP12
set_property PACKAGE_PIN U18 [get_ports M_DATA[0]]

# M2 - D2 -> M_DATA[2]
# IO Pin: IO_B13_LN18
set_property PACKAGE_PIN Y11 [get_ports M_DATA[1]]

# M4 - D4 -> M_DATA[4]
# IO Pin: IO_B34_LN14
set_property PACKAGE_PIN P20 [get_ports M_DATA[2]]

# M6 - D6 -> M_DATA[6]
# IO Pin: IO_B34_LP18
set_property PACKAGE_PIN V16 [get_ports M_DATA[3]]

# M8 - D8 -> M_DATA[8]
# IO Pin: IO_B13_LN14
set_property PACKAGE_PIN Y8 [get_ports M_DATA[4]]

# M10 - D10 -> M_DATA[10]
# IO Pin: IO_B13_0
set_property PACKAGE_PIN V5 [get_ports M_DATA[5]]

# M12 - D12 -> M_DATA[12]
# IO Pin: IO_B13_LN20
set_property PACKAGE_PIN Y13 [get_ports M_DATA[6]]

# M14 - D14 -> M_DATA[14]
# IO Pin: IO_B34_LP15
set_property PACKAGE_PIN T20 [get_ports M_DATA[7]]

# M16 - D16 -> M_DATA[16]
# IO Pin: IO_B34_LN12
set_property PACKAGE_PIN U19 [get_ports M_DATA[8]]

# M18 - D18 -> M_DATA[18]
# IO Pin: IO_B34_LP21
set_property PACKAGE_PIN V17 [get_ports M_DATA[9]]

# M20 - D20 -> M_DATA[20]
# IO Pin: IO_B34_LP20
set_property PACKAGE_PIN T17 [get_ports M_DATA[10]]

# M22 - D22 -> M_DATA[22]
# IO Pin: IO_B13_LN13
set_property PACKAGE_PIN Y6 [get_ports M_DATA[11]]

# M24 - D24 -> M_DATA[24]
# IO Pin: IO_B13_LP13
set_property PACKAGE_PIN Y7 [get_ports M_DATA[12]]

# M26 - D26 -> M_DATA[26]
# IO Pin: IO_B13_LP18
set_property PACKAGE_PIN W11 [get_ports M_DATA[13]]

# M28 - D28 -> M_DATA[28]
# IO Pin: IO_B13_LN16
set_property PACKAGE_PIN W9 [get_ports M_DATA[14]]

# M30 - D30 -> M_DATA[30]
# IO Pin: IO_B34_LN15
set_property PACKAGE_PIN U20 [get_ports M_DATA[15]]

# M32 - D32 -> M_DATA[32]
# IO Pin: IO_B34_LN18
set_property PACKAGE_PIN R17 [get_ports M_DATA[16]]

# M34 - D34 -> M_DATA[34]
# IO Pin: IO_B34_LP24
set_property PACKAGE_PIN P15 [get_ports M_DATA[17]]

# M36 - D36 -> M_DATA[36]
# IO Pin: IO_B34_0
set_property PACKAGE_PIN R19 [get_ports M_DATA[18]]

# M38 - D38 -> M_DATA[38]
# IO Pin: IO_B34_LN24
set_property PACKAGE_PIN P16 [get_ports M_DATA[19]]

# M40 - D40 -> M_DATA[40]
# IO Pin: IO_B13_LN19
set_property PACKAGE_PIN U5 [get_ports M_DATA[20]]

# M42 - D42 -> M_DATA[42]
# IO Pin: IO_B13_LP19
set_property PACKAGE_PIN T5 [get_ports M_DATA[21]]

# M44 - D44 -> M_DATA[44]
# IO Pin: IO_B13_LN15
set_property PACKAGE_PIN W8 [get_ports M_DATA[22]]

# M46 - D46 -> M_DATA[46]
# IO Pin: IO_B13_LP14
set_property PACKAGE_PIN Y9 [get_ports M_DATA[23]]

# M48 - D48 -> M_DATA[48]
# IO Pin: IO_B13_LP20
set_property PACKAGE_PIN Y12 [get_ports M_DATA[24]]

# M50 - D50 -> M_DATA[50]
# IO Pin: IO_B13_LP16
set_property PACKAGE_PIN W10 [get_ports M_DATA[25]]

# M52 - D52 -> M_DATA[52]
# IO Pin: IO_B34_LP10
set_property PACKAGE_PIN V15 [get_ports M_DATA[26]]

# M54 - D54 -> M_DATA[54]
# IO Pin: IO_B34_LN20
set_property PACKAGE_PIN R18 [get_ports M_DATA[27]]

# M56 - D56 -> M_DATA[56]
# IO Pin: IO_B34_LN21
set_property PACKAGE_PIN V18 [get_ports M_DATA[28]]

# M58 - D58 -> M_DATA[58]
# IO Pin: IO_B34_25
set_property PACKAGE_PIN T19 [get_ports M_DATA[29]]


