# set_property CFGBVS VCCO [current_design]
# set_property CONFIG_VOLTAGE 3.3 [current_design]

# set_property SLEW SLOW [get_ports M1_DATA]
# set_property KEEPER true [get_ports M1_DATA]


# M59 M58 ------------D58

# MCLK0 - IO_B13_LP21 (BANK 13)
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_IN]
set_property PACKAGE_PIN U12 [get_ports SYNC_IN]
# MCLK1 - IO_B34_LP14 (BANK 34)
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_OUT]
set_property PACKAGE_PIN T12 [get_ports SYNC_OUT]

# MCLK2 - IO_B34_LP11 (BANK 34)
# MCLK0 - IO_B13_LP21 (BANK 13)
set_property IOSTANDARD LVCMOS33 [get_ports M0_CLK]
set_property PACKAGE_PIN V11 [get_ports M0_CLK]
# MCLK1 - IO_B34_LP14 (BANK 34)
set_property IOSTANDARD LVCMOS33 [get_ports M1_CLK]
set_property PACKAGE_PIN N20 [get_ports M1_CLK]
# MCLK2 - IO_B34_LP11 (BANK 34)
set_property IOSTANDARD LVCMOS33 [get_ports M2_CLK]
set_property PACKAGE_PIN U14 [get_ports M2_CLK]

# LED_DI - IO_B34_LN23 (BANK 34)
set_property IOSTANDARD LVCMOS33 [get_ports LEDS]
set_property PACKAGE_PIN P18 [get_ports LEDS]

set_property IOSTANDARD LVCMOS33 [get_ports {M_DATA[*]}]

# Generated by MicArrayTool
# Selection: 12 microphones
# Microphone indices: [37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59]

# M37 - D36 -> M_DATA[0]
# IO Pin: IO_B34_0
set_property PACKAGE_PIN R19 [get_ports M_DATA[0]]

# M39 - D38 -> M_DATA[1]
# IO Pin: IO_B34_LN24
set_property PACKAGE_PIN P16 [get_ports M_DATA[1]]

# M41 - D40 -> M_DATA[2]
# IO Pin: IO_B13_LN19
set_property PACKAGE_PIN U5 [get_ports M_DATA[2]]

# M43 - D42 -> M_DATA[3]
# IO Pin: IO_B13_LP19
set_property PACKAGE_PIN T5 [get_ports M_DATA[3]]

# M45 - D44 -> M_DATA[4]
# IO Pin: IO_B13_LN15
set_property PACKAGE_PIN W8 [get_ports M_DATA[4]]

# M47 - D46 -> M_DATA[5]
# IO Pin: IO_B13_LP14
set_property PACKAGE_PIN Y9 [get_ports M_DATA[5]]

# M49 - D48 -> M_DATA[6]
# IO Pin: IO_B13_LP20
set_property PACKAGE_PIN Y12 [get_ports M_DATA[6]]

# M51 - D50 -> M_DATA[7]
# IO Pin: IO_B13_LP16
set_property PACKAGE_PIN W10 [get_ports M_DATA[7]]

# M53 - D52 -> M_DATA[8]
# IO Pin: IO_B34_LP10
set_property PACKAGE_PIN V15 [get_ports M_DATA[8]]

# M55 - D54 -> M_DATA[9]
# IO Pin: IO_B34_LN20
set_property PACKAGE_PIN R18 [get_ports M_DATA[9]]

# M57 - D56 -> M_DATA[10]
# IO Pin: IO_B34_LN21
set_property PACKAGE_PIN V18 [get_ports M_DATA[10]]

# M59 - D58 -> M_DATA[11]
# IO Pin: IO_B34_25
set_property PACKAGE_PIN T19 [get_ports M_DATA[11]]
