---
name: sesenta
board: boards/myir

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/axis_variable_v1_0
  - fpga/cores/tlast_gen_dyn_v1_0
  - fpga/cores/buffer_simple_v1_0
memory:
  - name: control
    range: 2K
    offset: '0x60000000'
  - name: status
    range: 2K
    offset: '0x50001000'
  - name: ram
    offset: '0x1E000000'
    range: 32M
  - name: dma
    offset: '0x40400000'
    range: 64K
  - name: axi_hp0
    offset: '0xF8008000'
    range: 4K



control_registers:
  - trig0
  - trig1
  - trig2
  - n_samples

status_registers:
  - mode

parameters:
  fclk0: 125000000 # FPGA clock speed in Hz

xdc:
  - boards/myir/config/ports.xdc

drivers:
  - server/drivers/common.hpp
  - server/drivers/dma-s2mm.hpp
  - ./sesenta.hpp

