---
name: sesenta
board: boards/myir

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/axis_variable_v1_0
memory:
  - name: control
    range: 2K
    offset: '0x60000000'
  - name: status
    range: 2K
    offset: '0x50001000'
  - name: mic1
    range: 16K
    offset: '0x40040000'
  - name: mic2
    range: 16K
    offset: '0x40060000'
  - name: mic3
    range: 16K
    offset: '0x40080000'
  - name: mic4
    range: 16K
    offset: '0x40100000'
  - name: mic5
    range: 16K
    offset: '0x40120000'
  - name: mic6
    range: 16K
    offset: '0x40140000'
  - name: mic7
    range: 16K
    offset: '0x40160000'
  - name: mic8
    range: 16K
    offset: '0x40180000'


control_registers:
  - led
  - trig0
  - trig1

status_registers:
  - mode

parameters:
  fclk0: 125000000 # FPGA clock speed in Hz

xdc:
  - boards/myir/config/ports.xdc

drivers:
  - server/drivers/common.hpp
  - ./sesenta.hpp
