
// autogenerated
module delay_config #(
    parameter DELAY_SELECT = 0
)(
    output wire [63:0] delays  // 16 x 4-bit delays packed
);

  // Function to pack 16 4-bit delays into 64 bits
  function [63:0] pack_delays;
    input [3:0] d0, d1, d2, d3, d4, d5, d6, d7;
    input [3:0] d8, d9, d10, d11, d12, d13, d14, d15;
    begin
      pack_delays = {d15, d14, d13, d12, d11, d10, d9, d8, d7, d6, d5, d4, d3, d2, d1, d0};
    end
  endfunction

  // Delay configurations for all 16 source directions
  // Mics: M18  M19  M20  M21  M22  M23  M24  M25  M26  M27  M28  M29  M30  M31  M34  M35
  localparam [63:0] DELAY_CONFIG_0  = pack_delays(0,0,1,1,2,3,4,4,5,5,5,5,4,3,1,0);  // Source M18
  localparam [63:0] DELAY_CONFIG_1  = pack_delays(0,0,0,1,1,2,3,4,5,5,5,5,4,4,1,1);  // Source M19
  localparam [63:0] DELAY_CONFIG_2  = pack_delays(1,0,0,0,1,2,2,3,5,5,5,6,5,5,2,2);  // Source M20
  localparam [63:0] DELAY_CONFIG_3  = pack_delays(1,1,0,0,0,1,1,2,3,4,4,5,5,5,3,2);  // Source M21
  localparam [63:0] DELAY_CONFIG_4  = pack_delays(2,1,1,0,0,0,1,1,2,3,4,5,5,5,4,3);  // Source M22
  localparam [63:0] DELAY_CONFIG_5  = pack_delays(3,2,2,1,0,0,0,1,2,2,3,5,5,5,5,5);  // Source M23
  localparam [63:0] DELAY_CONFIG_6  = pack_delays(4,3,2,1,1,0,0,0,1,1,2,3,4,4,5,5);  // Source M24
  localparam [63:0] DELAY_CONFIG_7  = pack_delays(4,4,3,2,1,1,0,0,0,1,1,2,3,4,5,5);  // Source M25
  localparam [63:0] DELAY_CONFIG_8  = pack_delays(5,5,5,3,2,2,1,0,0,0,1,2,2,3,5,6);  // Source M26
  localparam [63:0] DELAY_CONFIG_9  = pack_delays(5,5,5,4,3,2,1,1,0,0,0,1,1,2,4,5);  // Source M27
  localparam [63:0] DELAY_CONFIG_10 = pack_delays(5,5,5,4,4,3,2,1,1,0,0,0,1,1,4,5);  // Source M28
  localparam [63:0] DELAY_CONFIG_11 = pack_delays(5,5,6,5,5,5,3,2,2,1,0,0,0,1,3,5);  // Source M29
  localparam [63:0] DELAY_CONFIG_12 = pack_delays(4,4,5,5,5,5,4,3,2,1,1,0,0,0,2,3);  // Source M30
  localparam [63:0] DELAY_CONFIG_13 = pack_delays(3,4,5,5,5,5,4,4,3,2,1,1,0,0,1,2);  // Source M31
  localparam [63:0] DELAY_CONFIG_14 = pack_delays(1,1,2,3,4,5,5,5,5,4,4,3,2,1,0,0);  // Source M34
  localparam [63:0] DELAY_CONFIG_15 = pack_delays(0,1,2,2,3,5,5,5,6,5,5,5,3,2,0,0);  // Source M35

  // Select the appropriate delay configuration
  assign delays = 
    (DELAY_SELECT == 0 ) ? DELAY_CONFIG_0  :
    (DELAY_SELECT == 1 ) ? DELAY_CONFIG_1  :
    (DELAY_SELECT == 2 ) ? DELAY_CONFIG_2  :
    (DELAY_SELECT == 3 ) ? DELAY_CONFIG_3  :
    (DELAY_SELECT == 4 ) ? DELAY_CONFIG_4  :
    (DELAY_SELECT == 5 ) ? DELAY_CONFIG_5  :
    (DELAY_SELECT == 6 ) ? DELAY_CONFIG_6  :
    (DELAY_SELECT == 7 ) ? DELAY_CONFIG_7  :
    (DELAY_SELECT == 8 ) ? DELAY_CONFIG_8  :
    (DELAY_SELECT == 9 ) ? DELAY_CONFIG_9  :
    (DELAY_SELECT == 10) ? DELAY_CONFIG_10 :
    (DELAY_SELECT == 11) ? DELAY_CONFIG_11 :
    (DELAY_SELECT == 12) ? DELAY_CONFIG_12 :
    (DELAY_SELECT == 13) ? DELAY_CONFIG_13 :
    (DELAY_SELECT == 14) ? DELAY_CONFIG_14 :
    (DELAY_SELECT == 15) ? DELAY_CONFIG_15 :
    64'h0;

endmodule