/* Generated by Yosys 0.32+49 (git sha1 cbd3ff2d3, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* \amaranth.hierarchy  = "pdm_cic.cic" *)
(* generator = "Amaranth" *)
module cic(strobe_in, strobe_out, signal_out, rst, clk, signal_in);
  reg \$auto$verilog_backend.cc:2184:dump_module$29  = 0;
  wire [32:0] \$1 ;
  wire [32:0] \$10 ;
  wire [32:0] \$11 ;
  wire [32:0] \$13 ;
  wire [32:0] \$14 ;
  wire \$16 ;
  wire [6:0] \$18 ;
  wire [6:0] \$19 ;
  wire [32:0] \$2 ;
  wire \$21 ;
  wire [32:0] \$23 ;
  wire [32:0] \$24 ;
  wire [32:0] \$26 ;
  wire [32:0] \$27 ;
  wire [32:0] \$29 ;
  wire [32:0] \$30 ;
  wire [32:0] \$32 ;
  wire [32:0] \$33 ;
  wire [32:0] \$35 ;
  wire [32:0] \$36 ;
  wire [31:0] \$38 ;
  wire [32:0] \$4 ;
  wire [32:0] \$5 ;
  wire [32:0] \$7 ;
  wire [32:0] \$8 ;
  input clk;
  wire clk;
  reg comb_edge = 1'h0;
  reg \comb_edge$next ;
  reg [5:0] decimate_counter = 6'h00;
  reg [5:0] \decimate_counter$next ;
  reg [31:0] dy0 = 32'd0;
  reg [31:0] \dy0$next ;
  reg [31:0] dy1 = 32'd0;
  reg [31:0] \dy1$next ;
  reg [31:0] dy2 = 32'd0;
  reg [31:0] \dy2$next ;
  reg [31:0] dy3 = 32'd0;
  reg [31:0] \dy3$next ;
  reg [31:0] dy4 = 32'd0;
  reg [31:0] \dy4$next ;
  input rst;
  wire rst;
  input [31:0] signal_in;
  wire [31:0] signal_in;
  output [31:0] signal_out;
  reg [31:0] signal_out = 32'd0;
  reg [31:0] \signal_out$next ;
  input strobe_in;
  wire strobe_in;
  output strobe_out;
  reg strobe_out = 1'h0;
  reg \strobe_out$next ;
  reg [31:0] x0 = 32'd0;
  reg [31:0] \x0$next ;
  reg [31:0] x1 = 32'd0;
  reg [31:0] \x1$next ;
  reg [31:0] x2 = 32'd0;
  reg [31:0] \x2$next ;
  reg [31:0] x3 = 32'd0;
  reg [31:0] \x3$next ;
  reg [31:0] x4 = 32'd0;
  reg [31:0] \x4$next ;
  reg [31:0] y0 = 32'd0;
  reg [31:0] \y0$next ;
  reg [31:0] y1 = 32'd0;
  reg [31:0] \y1$next ;
  reg [31:0] y2 = 32'd0;
  reg [31:0] \y2$next ;
  reg [31:0] y3 = 32'd0;
  reg [31:0] \y3$next ;
  reg [31:0] y4 = 32'd0;
  reg [31:0] \y4$next ;
  assign \$11  = $signed(x2) + $signed(x3);
  assign \$14  = $signed(x3) + $signed(x4);
  assign \$16  = decimate_counter < 6'h3f;
  assign \$19  = decimate_counter + 1'h1;
  assign \$21  = decimate_counter < 6'h3f;
  assign \$24  = $signed(x4) - $signed(dy0);
  assign \$27  = $signed(y0) - $signed(dy1);
  assign \$2  = $signed(signal_in) + $signed(x0);
  assign \$30  = $signed(y1) - $signed(dy2);
  assign \$33  = $signed(y2) - $signed(dy3);
  assign \$36  = $signed(y3) - $signed(dy4);
  assign \$5  = $signed(x0) + $signed(x1);
  assign \$8  = $signed(x1) + $signed(x2);
  always @(posedge clk)
    dy2 <= \dy2$next ;
  always @(posedge clk)
    dy1 <= \dy1$next ;
  always @(posedge clk)
    dy0 <= \dy0$next ;
  always @(posedge clk)
    signal_out <= \signal_out$next ;
  always @(posedge clk)
    y4 <= \y4$next ;
  always @(posedge clk)
    y3 <= \y3$next ;
  always @(posedge clk)
    y2 <= \y2$next ;
  always @(posedge clk)
    y1 <= \y1$next ;
  always @(posedge clk)
    y0 <= \y0$next ;
  always @(posedge clk)
    comb_edge <= \comb_edge$next ;
  always @(posedge clk)
    decimate_counter <= \decimate_counter$next ;
  always @(posedge clk)
    x4 <= \x4$next ;
  always @(posedge clk)
    x3 <= \x3$next ;
  always @(posedge clk)
    x2 <= \x2$next ;
  always @(posedge clk)
    x1 <= \x1$next ;
  always @(posedge clk)
    x0 <= \x0$next ;
  always @(posedge clk)
    strobe_out <= \strobe_out$next ;
  always @(posedge clk)
    dy4 <= \dy4$next ;
  always @(posedge clk)
    dy3 <= \dy3$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \strobe_out$next  = comb_edge;
    casez (rst)
      1'h1:
          \strobe_out$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \x0$next  = x0;
    casez (strobe_in)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:75" */
      1'h1:
          \x0$next  = \$2 [31:0];
    endcase
    casez (rst)
      1'h1:
          \x0$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \y2$next  = y2;
    casez (comb_edge)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:85" */
      1'h1:
          \y2$next  = \$30 [31:0];
    endcase
    casez (rst)
      1'h1:
          \y2$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \y3$next  = y3;
    casez (comb_edge)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:85" */
      1'h1:
          \y3$next  = \$33 [31:0];
    endcase
    casez (rst)
      1'h1:
          \y3$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \y4$next  = y4;
    casez (comb_edge)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:85" */
      1'h1:
          \y4$next  = \$36 [31:0];
    endcase
    casez (rst)
      1'h1:
          \y4$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \signal_out$next  = signal_out;
    casez (comb_edge)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:85" */
      1'h1:
          \signal_out$next  = \$38 ;
    endcase
    casez (rst)
      1'h1:
          \signal_out$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \dy0$next  = dy0;
    casez (comb_edge)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:85" */
      1'h1:
          \dy0$next  = x4;
    endcase
    casez (rst)
      1'h1:
          \dy0$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \dy1$next  = dy1;
    casez (comb_edge)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:85" */
      1'h1:
          \dy1$next  = y0;
    endcase
    casez (rst)
      1'h1:
          \dy1$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \dy2$next  = dy2;
    casez (comb_edge)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:85" */
      1'h1:
          \dy2$next  = y1;
    endcase
    casez (rst)
      1'h1:
          \dy2$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \dy3$next  = dy3;
    casez (comb_edge)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:85" */
      1'h1:
          \dy3$next  = y2;
    endcase
    casez (rst)
      1'h1:
          \dy3$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \dy4$next  = dy4;
    casez (comb_edge)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:85" */
      1'h1:
          \dy4$next  = y3;
    endcase
    casez (rst)
      1'h1:
          \dy4$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \x1$next  = x1;
    casez (strobe_in)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:75" */
      1'h1:
          \x1$next  = \$5 [31:0];
    endcase
    casez (rst)
      1'h1:
          \x1$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \x2$next  = x2;
    casez (strobe_in)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:75" */
      1'h1:
          \x2$next  = \$8 [31:0];
    endcase
    casez (rst)
      1'h1:
          \x2$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \x3$next  = x3;
    casez (strobe_in)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:75" */
      1'h1:
          \x3$next  = \$11 [31:0];
    endcase
    casez (rst)
      1'h1:
          \x3$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \x4$next  = x4;
    casez (strobe_in)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:75" */
      1'h1:
          \x4$next  = \$14 [31:0];
    endcase
    casez (rst)
      1'h1:
          \x4$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \decimate_counter$next  = decimate_counter;
    casez (strobe_in)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:75" */
      1'h1:
          (* full_case = 32'd1 *)
          casez (\$16 )
            /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:78" */
            1'h1:
                \decimate_counter$next  = \$19 [5:0];
            /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:81" */
            default:
                \decimate_counter$next  = 6'h00;
          endcase
    endcase
    casez (rst)
      1'h1:
          \decimate_counter$next  = 6'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \comb_edge$next  = comb_edge;
    casez (strobe_in)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:75" */
      1'h1:
          (* full_case = 32'd1 *)
          casez (\$21 )
            /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:78" */
            1'h1:
                /* empty */;
            /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:81" */
            default:
                \comb_edge$next  = 1'h1;
          endcase
    endcase
    casez (comb_edge)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:85" */
      1'h1:
          \comb_edge$next  = 1'h0;
    endcase
    casez (rst)
      1'h1:
          \comb_edge$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \y0$next  = y0;
    casez (comb_edge)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:85" */
      1'h1:
          \y0$next  = \$24 [31:0];
    endcase
    casez (rst)
      1'h1:
          \y0$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$29 ) begin end
    \y1$next  = y1;
    casez (comb_edge)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/amlib/dsp/fixedpointcicfilter.py:85" */
      1'h1:
          \y1$next  = \$27 [31:0];
    endcase
    casez (rst)
      1'h1:
          \y1$next  = 32'd0;
    endcase
  end
  assign \$1  = \$2 ;
  assign \$4  = \$5 ;
  assign \$7  = \$8 ;
  assign \$10  = \$11 ;
  assign \$13  = \$14 ;
  assign \$18  = \$19 ;
  assign \$23  = \$24 ;
  assign \$26  = \$27 ;
  assign \$29  = \$30 ;
  assign \$32  = \$33 ;
  assign \$35  = \$36 ;
  assign \$38  = y4;
endmodule

(* \amaranth.hierarchy  = "pdm_cic.clk_divider" *)
(* generator = "Amaranth" *)
module clk_divider(clock_out, rst, clk, clock_enable_in);
  reg \$auto$verilog_backend.cc:2184:dump_module$30  = 0;
  wire \$1 ;
  wire \$3 ;
  wire \$5 ;
  wire [5:0] \$7 ;
  wire [5:0] \$8 ;
  input clk;
  wire clk;
  reg [4:0] clock_counter = 5'h00;
  reg [4:0] \clock_counter$next ;
  input clock_enable_in;
  wire clock_enable_in;
  output clock_out;
  reg clock_out = 1'h0;
  reg \clock_out$next ;
  input rst;
  wire rst;
  assign \$1  = clock_counter >= 5'h13;
  assign \$3  = ~ clock_out;
  assign \$5  = clock_counter >= 5'h13;
  assign \$8  = clock_counter + 1'h1;
  always @(posedge clk)
    clock_counter <= \clock_counter$next ;
  always @(posedge clk)
    clock_out <= \clock_out$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$30 ) begin end
    \clock_out$next  = clock_out;
    casez (\$1 )
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/test/clockdivider.py:20" */
      1'h1:
          (* full_case = 32'd1 *)
          casez (clock_enable_in)
            /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/test/clockdivider.py:21" */
            1'h1:
                \clock_out$next  = \$3 ;
            /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/test/clockdivider.py:23" */
            default:
                \clock_out$next  = 1'h0;
          endcase
    endcase
    casez (rst)
      1'h1:
          \clock_out$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$30 ) begin end
    (* full_case = 32'd1 *)
    casez (\$5 )
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/test/clockdivider.py:20" */
      1'h1:
          \clock_counter$next  = 5'h00;
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/test/clockdivider.py:28" */
      default:
          \clock_counter$next  = \$8 [4:0];
    endcase
    casez (rst)
      1'h1:
          \clock_counter$next  = 5'h00;
    endcase
  end
  assign \$7  = \$8 ;
endmodule

(* \amaranth.hierarchy  = "pdm_cic" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module pdm_cic(pdm_clock_in, pdm_data_in, pcm_strobe_out, pcm_data_out, pdm_clock_out, clk, rst, pdm_clock_in_en);
  reg \$auto$verilog_backend.cc:2184:dump_module$31  = 0;
  wire \$1 ;
  wire \$3 ;
  wire \$5 ;
  wire \$7 ;
  (* \amaranth.sample_reg  = 32'd1 *)
  reg \$sample$s$base_clock$sync$1  = 1'h0;
  wire \$sample$s$base_clock$sync$1$next ;
  wire base_clock;
  reg [31:0] cic_signal_in;
  wire [31:0] cic_signal_out;
  wire cic_strobe_in;
  wire cic_strobe_out;
  input clk;
  wire clk;
  wire clk_divider_clock_enable_in;
  wire clk_divider_clock_out;
  output [31:0] pcm_data_out;
  reg [31:0] pcm_data_out = 32'd0;
  reg [31:0] \pcm_data_out$next ;
  output pcm_strobe_out;
  wire pcm_strobe_out;
  input pdm_clock_in;
  wire pdm_clock_in;
  input pdm_clock_in_en;
  wire pdm_clock_in_en;
  reg pdm_clock_in_sy0 = 1'h0;
  reg \pdm_clock_in_sy0$next ;
  reg pdm_clock_in_sy1 = 1'h0;
  reg \pdm_clock_in_sy1$next ;
  output pdm_clock_out;
  reg pdm_clock_out = 1'h0;
  reg \pdm_clock_out$next ;
  input pdm_data_in;
  wire pdm_data_in;
  reg pdm_data_in_sy0 = 1'h0;
  reg \pdm_data_in_sy0$next ;
  reg pdm_data_in_sy1 = 1'h0;
  reg \pdm_data_in_sy1$next ;
  input rst;
  wire rst;
  wire strobe_out;
  assign \$1  = ~ pdm_clock_in_en;
  assign \$3  = pdm_clock_in_en ? pdm_clock_in_sy1 : clk_divider_clock_out;
  assign \$5  = ~ \$sample$s$base_clock$sync$1 ;
  assign \$7  = \$5  & base_clock;
  always @(posedge clk)
    \$sample$s$base_clock$sync$1  <= \$3 ;
  always @(posedge clk)
    pcm_data_out <= \pcm_data_out$next ;
  always @(posedge clk)
    pdm_data_in_sy1 <= \pdm_data_in_sy1$next ;
  always @(posedge clk)
    pdm_data_in_sy0 <= \pdm_data_in_sy0$next ;
  always @(posedge clk)
    pdm_clock_out <= \pdm_clock_out$next ;
  always @(posedge clk)
    pdm_clock_in_sy1 <= \pdm_clock_in_sy1$next ;
  always @(posedge clk)
    pdm_clock_in_sy0 <= \pdm_clock_in_sy0$next ;
  cic cic (
    .clk(clk),
    .rst(rst),
    .signal_in(cic_signal_in),
    .signal_out(cic_signal_out),
    .strobe_in(cic_strobe_in),
    .strobe_out(cic_strobe_out)
  );
  clk_divider clk_divider (
    .clk(clk),
    .clock_enable_in(clk_divider_clock_enable_in),
    .clock_out(clk_divider_clock_out),
    .rst(rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$31 ) begin end
    \pdm_clock_in_sy0$next  = pdm_clock_in;
    casez (rst)
      1'h1:
          \pdm_clock_in_sy0$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$31 ) begin end
    \pcm_data_out$next  = pcm_data_out;
    casez (strobe_out)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/pdm_cic2.py:125" */
      1'h1:
          \pcm_data_out$next  = cic_signal_out;
    endcase
    casez (rst)
      1'h1:
          \pcm_data_out$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$31 ) begin end
    \pdm_clock_in_sy1$next  = pdm_clock_in_sy0;
    casez (rst)
      1'h1:
          \pdm_clock_in_sy1$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$31 ) begin end
    \pdm_clock_out$next  = clk_divider_clock_out;
    casez (rst)
      1'h1:
          \pdm_clock_out$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$31 ) begin end
    \pdm_data_in_sy0$next  = pdm_data_in;
    casez (rst)
      1'h1:
          \pdm_data_in_sy0$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$31 ) begin end
    \pdm_data_in_sy1$next  = pdm_data_in_sy0;
    casez (rst)
      1'h1:
          \pdm_data_in_sy1$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$31 ) begin end
    (* full_case = 32'd1 *)
    casez (pdm_data_in_sy1)
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/pdm_cic2.py:114" */
      1'h1:
          cic_signal_in = 32'd1;
      /* src = "/home/tucanae47/gitprojects/Q_record_transient_mix2/mic_characterization/pdm_cic2.py:116" */
      default:
          cic_signal_in = 32'd4294967295;
    endcase
  end
  assign \$sample$s$base_clock$sync$1$next  = base_clock;
  assign pcm_strobe_out = strobe_out;
  assign strobe_out = cic_strobe_out;
  assign cic_strobe_in = \$7 ;
  assign base_clock = \$3 ;
  assign clk_divider_clock_enable_in = \$1 ;
endmodule
